// 生成 component/src/index.js 与 component/src/client.js:
// 把 ../src/host.js 和 ../src/client.js 包装成 DSH 静态组件插件的 Host/Client 模块。
// 用法:node component/build.js
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

const host = readFileSync(join(root, 'src', 'host.js'), 'utf8')
const client = readFileSync(join(root, 'src', 'client.js'), 'utf8')

const hostModule = `// Generated by component/build.js from ../src/host.js — do not edit directly.
// DSH 静态组件插件 Host 半区:通过 /mindmap RPC channel 暴露原动态插件 handler。
const HOST_BODY = ${JSON.stringify(host)}

export const name = 'time-line-mind'

export const inject = ['connection']

export function apply(ctx) {
  const handlers = {}
  const harness = {
    handle(method, fn) { handlers[method] = fn },
    defineTool(spec) { return spec },
    registerTool() {},
  }
  const factory = new Function('harness', HOST_BODY)
  const plugin = factory(harness)
  plugin.apply(ctx)

  const connection = ctx.get('connection')
  if (!connection || !connection.rpc) return
  const remove = connection.rpc.handle(
    '/mindmap',
    async (endpoint, payload, signal) => {
      const handler = handlers[endpoint]
      if (!handler) {
        return { ok: false, error: { code: 'NOT_FOUND', message: 'unknown mindmap endpoint: ' + endpoint } }
      }
      try {
        const value = await handler(payload || {}, { signal })
        return { ok: true, value }
      } catch (err) {
        return {
          ok: false,
          error: {
            code: (err && err.code) || 'ERROR',
            message: err && err.message ? String(err.message) : String(err),
          },
        }
      }
    },
    { authority: 'trusted-host' },
  )
  ctx.effect(() => () => { void remove() }, 'time-line-mind: rpc channel')
}
`

const clientModule = `// Generated by component/build.js from ../src/client.js — do not edit directly.
// DSH 静态组件插件 Client 半区(ModuleLoader bundle):包装原动态客户端代码,把 host.call 路由到 /mindmap RPC channel。
window.__ModuleLoader__.load({
  id: 'time-line-mind',
  factory: (require) => {
    const React = require('react')
    const CLIENT_BODY = ${JSON.stringify(client)}
    const inject = ['slots', 'connection']

    function apply(ctx) {
      let styleEl = null
      const styles = {
        insert(css) {
          try {
            if (typeof document === 'undefined') return
            if (!styleEl) {
              styleEl = document.createElement('style')
              styleEl.setAttribute('data-time-line-mind', '')
              document.head.appendChild(styleEl)
            }
            styleEl.textContent += css
          } catch (err) {
            console.error('time-line-mind style insert failed', err)
          }
        },
      }
      const host = {
        async call(method, args) {
          const connection = ctx.get('connection')
          if (!connection || !connection.rpc) throw new Error('connection unavailable')
          const result = await connection.rpc.call('/mindmap', method, args ?? {})
          if (!result.ok) {
            const err = new Error(
              (result.error && (result.error.message || result.error.code)) || 'mindmap rpc error',
            )
            err.code = result.error && result.error.code
            throw err
          }
          return result.value
        },
      }
      ctx.effect(() => () => { if (styleEl) styleEl.remove() }, 'time-line-mind: style')
      const factory = new Function('React', 'host', 'styles', CLIENT_BODY)
      const plugin = factory(React, host, styles)
      globalThis.__TIME_LINE_MIND_STATIC__ = true
      plugin.apply(ctx)
    }

    return { inject, apply }
  },
})
`

mkdirSync(join(here, 'src'), { recursive: true })
writeFileSync(join(here, 'src', 'index.js'), hostModule)
writeFileSync(join(here, 'src', 'client.js'), clientModule)
console.log('component/src/index.js and component/src/client.js generated')
